[package]
name = "muxy-pty"
description = "Pseudo-terminal boundary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
portable-pty = "0.9"
