//! Shared shortcut catalog and configuration interface. No UI or app dependencies.

pub const WORKSPACE_CLIPBOARD_CONTEXT: &str =
    "WorkspaceTabs && !TextInput && !BareInput && !MultilineInput && !TerminalSearchInput";

#[derive(Clone, Copy, Debug)]
pub struct Shortcut {
    pub id: &'static str,
    pub keys: &'static [&'static str],
    pub contexts: &'static [Option<&'static str>],
    pub key_contexts: &'static [&'static [Option<&'static str>]],
}

pub trait ShortcutSettings {
    fn keys(&self, id: &str, context: Option<&str>) -> Vec<String>;
}

#[derive(Debug)]
pub struct Defaults;

impl ShortcutSettings for Defaults {
    fn keys(&self, id: &str, context: Option<&str>) -> Vec<String> {
        find(id).map_or_else(Vec::new, |shortcut| {
            shortcut
                .keys
                .iter()
                .zip(shortcut.key_contexts)
                .filter(|(_, contexts)| contexts.contains(&context))
                .map(|(key, _)| (*key).to_owned())
                .collect()
        })
    }
}

pub fn find(id: &str) -> Option<&'static Shortcut> {
    ALL.iter().find(|shortcut| shortcut.id == id)
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ShortcutId {
    NewTab,
    CloseTab,
    SplitRight,
    SplitDown,
    FocusPaneLeft,
    FocusPaneRight,
    FocusPaneUp,
    FocusPaneDown,
    ToggleZoomPane,
    ClosePane,
    NextTab,
    PreviousTab,
    PreviousProject,
    NextProject,
    AddProject,
    SelectTab1,
    SelectTab2,
    SelectTab3,
    SelectTab4,
    SelectTab5,
    SelectTab6,
    SelectTab7,
    SelectTab8,
    SelectTab9,
    Copy,
    Paste,
    Find,
    FindNext,
    FindPrevious,
    ScrollToBottom,
    IncreaseFontSize,
    DecreaseFontSize,
    NewHomeTab,
    ToggleSidebar,
    ToggleFullScreen,
    ToggleThemePicker,
    NavigateBack,
    NavigateForward,
    Quit,
    HideApp,
    HideOthers,
    Minimize,
    TextInputBackspace,
    TextInputDelete,
    TextInputLeft,
    TextInputRight,
    TextInputWordLeft,
    TextInputWordRight,
    TextInputHome,
    TextInputEnd,
    TextInputSelectLeft,
    TextInputSelectRight,
    TextInputSelectWordLeft,
    TextInputSelectWordRight,
    TextInputSelectHome,
    TextInputSelectEnd,
    TextInputSelectAll,
    TextInputCopy,
    TextInputCut,
    TextInputPaste,
    TextInputUndo,
    TextInputRedo,
    TextInputDocumentStart,
    TextInputDocumentEnd,
    TextInputShowCharacterPalette,
    TextInputInsertNewline,
    TextInputUp,
    TextInputDown,
    TextInputSelectUp,
    TextInputSelectDown,
    TextInputDeleteWord,
    TextInputPageUp,
    TextInputPageDown,
    TextInputSelectPageUp,
    TextInputSelectPageDown,
    TextInputSelectDocumentStart,
    TextInputSelectDocumentEnd,
    TextInputSubmit,
    TextInputCancel,
    PopoverSelectNext,
    PopoverSelectPrevious,
    PopoverConfirm,
    PopoverSecondaryConfirm,
    PopoverTabPressed,
    PopoverNavigateBack,
    PopoverDismiss,
    PopoverNextTab,
    PopoverPreviousTab,
    MenuDismissMenu,
    MenuHighlightPrevious,
    MenuHighlightNext,
    MenuConfirmHighlighted,
    ProjectColorsPreviousColor,
    ProjectColorsNextColor,
    ProjectColorsChooseColor,
    ProjectColorsDismissColors,
    ButtonActivate,
    EndAllSessionsAndQuit,
    ShowAll,
    Zoom,
    OpenConfiguration,
    TerminalCloseFind,
}

impl ShortcutId {
    pub fn definition(self) -> &'static Shortcut {
        &ALL[self as usize]
    }
}

pub const ALL: &[Shortcut] = &[
    Shortcut {
        id: "new_tab",
        keys: &["cmd-t"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "close_tab",
        keys: &["cmd-shift-w"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "split_right",
        keys: &["cmd-d"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "split_down",
        keys: &["cmd-shift-d"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "focus_pane_left",
        keys: &["cmd-alt-left"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "focus_pane_right",
        keys: &["cmd-alt-right"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "focus_pane_up",
        keys: &["cmd-alt-up"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "focus_pane_down",
        keys: &["cmd-alt-down"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "toggle_zoom_pane",
        keys: &["cmd-shift-enter"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "close_pane",
        keys: &["cmd-w"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "next_tab",
        keys: &["cmd-]", "ctrl-tab"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")], &[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "previous_tab",
        keys: &["cmd-[", "ctrl-shift-tab"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")], &[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "previous_project",
        keys: &["cmd-alt-["],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "next_project",
        keys: &["cmd-alt-]"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "add_project",
        keys: &["cmd-o"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "select_tab1",
        keys: &["cmd-1"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "select_tab2",
        keys: &["cmd-2"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "select_tab3",
        keys: &["cmd-3"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "select_tab4",
        keys: &["cmd-4"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "select_tab5",
        keys: &["cmd-5"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "select_tab6",
        keys: &["cmd-6"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "select_tab7",
        keys: &["cmd-7"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "select_tab8",
        keys: &["cmd-8"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "select_tab9",
        keys: &["cmd-9"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "copy",
        keys: &["cmd-c"],
        contexts: &[Some(WORKSPACE_CLIPBOARD_CONTEXT)],
        key_contexts: &[&[Some(WORKSPACE_CLIPBOARD_CONTEXT)]],
    },
    Shortcut {
        id: "paste",
        keys: &["cmd-v"],
        contexts: &[Some(WORKSPACE_CLIPBOARD_CONTEXT)],
        key_contexts: &[&[Some(WORKSPACE_CLIPBOARD_CONTEXT)]],
    },
    Shortcut {
        id: "find",
        keys: &["cmd-f"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "find_next",
        keys: &["cmd-g"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "find_previous",
        keys: &["cmd-shift-g"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "scroll_to_bottom",
        keys: &["cmd-end"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "increase_font_size",
        keys: &["cmd-+", "cmd-=", "cmd-shift-="],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[
            &[Some("WorkspaceTabs")],
            &[Some("WorkspaceTabs")],
            &[Some("WorkspaceTabs")],
        ],
    },
    Shortcut {
        id: "decrease_font_size",
        keys: &["cmd--"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "new_home_tab",
        keys: &["cmd-n"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "toggle_sidebar",
        keys: &["cmd-b"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "toggle_full_screen",
        keys: &["cmd-ctrl-f"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "toggle_theme_picker",
        keys: &["cmd-shift-k"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "navigate_back",
        keys: &["cmd-ctrl-left"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "navigate_forward",
        keys: &["cmd-ctrl-right"],
        contexts: &[Some("WorkspaceTabs")],
        key_contexts: &[&[Some("WorkspaceTabs")]],
    },
    Shortcut {
        id: "quit",
        keys: &["cmd-q"],
        contexts: &[None],
        key_contexts: &[&[None]],
    },
    Shortcut {
        id: "hide_app",
        keys: &["cmd-h"],
        contexts: &[None],
        key_contexts: &[&[None]],
    },
    Shortcut {
        id: "hide_others",
        keys: &["cmd-alt-h"],
        contexts: &[None],
        key_contexts: &[&[None]],
    },
    Shortcut {
        id: "minimize",
        keys: &["cmd-m"],
        contexts: &[None],
        key_contexts: &[&[None]],
    },
    Shortcut {
        id: "text_input.backspace",
        keys: &["backspace"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.delete",
        keys: &["delete"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.left",
        keys: &["left"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.right",
        keys: &["right"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.word_left",
        keys: &["alt-left"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.word_right",
        keys: &["alt-right"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.home",
        keys: &["cmd-left"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.end",
        keys: &["cmd-right"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.select_left",
        keys: &["shift-left"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.select_right",
        keys: &["shift-right"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.select_word_left",
        keys: &["shift-alt-left"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.select_word_right",
        keys: &["shift-alt-right"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.select_home",
        keys: &["shift-cmd-left"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.select_end",
        keys: &["shift-cmd-right"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.select_all",
        keys: &["cmd-a"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.copy",
        keys: &["cmd-c"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.cut",
        keys: &["cmd-x"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.paste",
        keys: &["cmd-v"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.undo",
        keys: &["cmd-z"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.redo",
        keys: &["shift-cmd-z"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.document_start",
        keys: &["home", "cmd-up"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[
            &[
                Some("TextInput"),
                Some("BareInput"),
                Some("TerminalSearchInput"),
                Some("MultilineInput"),
            ],
            &[Some("MultilineInput")],
        ],
    },
    Shortcut {
        id: "text_input.document_end",
        keys: &["end", "cmd-down"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[
            &[
                Some("TextInput"),
                Some("BareInput"),
                Some("TerminalSearchInput"),
                Some("MultilineInput"),
            ],
            &[Some("MultilineInput")],
        ],
    },
    Shortcut {
        id: "text_input.show_character_palette",
        keys: &["ctrl-cmd-space"],
        contexts: &[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ],
        key_contexts: &[&[
            Some("TextInput"),
            Some("BareInput"),
            Some("TerminalSearchInput"),
            Some("MultilineInput"),
        ]],
    },
    Shortcut {
        id: "text_input.insert_newline",
        keys: &["enter"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.up",
        keys: &["up"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.down",
        keys: &["down"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.select_up",
        keys: &["shift-up"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.select_down",
        keys: &["shift-down"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.delete_word",
        keys: &["alt-backspace"],
        contexts: &[
            Some("MultilineInput"),
            Some("TextInput"),
            Some("TerminalSearchInput"),
        ],
        key_contexts: &[&[
            Some("MultilineInput"),
            Some("TextInput"),
            Some("TerminalSearchInput"),
        ]],
    },
    Shortcut {
        id: "text_input.page_up",
        keys: &["pageup"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.page_down",
        keys: &["pagedown"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.select_page_up",
        keys: &["shift-pageup"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.select_page_down",
        keys: &["shift-pagedown"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.select_document_start",
        keys: &["shift-cmd-up"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.select_document_end",
        keys: &["shift-cmd-down"],
        contexts: &[Some("MultilineInput")],
        key_contexts: &[&[Some("MultilineInput")]],
    },
    Shortcut {
        id: "text_input.submit",
        keys: &["enter"],
        contexts: &[Some("TextInput"), Some("TerminalSearchInput")],
        key_contexts: &[&[Some("TextInput"), Some("TerminalSearchInput")]],
    },
    Shortcut {
        id: "text_input.cancel",
        keys: &["escape"],
        contexts: &[Some("TextInput"), Some("TerminalSearchInput")],
        key_contexts: &[&[Some("TextInput"), Some("TerminalSearchInput")]],
    },
    Shortcut {
        id: "popover.select_next",
        keys: &["down"],
        contexts: &[Some("CommandPopover")],
        key_contexts: &[&[Some("CommandPopover")]],
    },
    Shortcut {
        id: "popover.select_previous",
        keys: &["up", "shift-tab"],
        contexts: &[Some("CommandPopover")],
        key_contexts: &[&[Some("CommandPopover")], &[Some("CommandPopover")]],
    },
    Shortcut {
        id: "popover.confirm",
        keys: &["enter"],
        contexts: &[Some("CommandPopover")],
        key_contexts: &[&[Some("CommandPopover")]],
    },
    Shortcut {
        id: "popover.secondary_confirm",
        keys: &["alt-enter", "cmd-enter"],
        contexts: &[Some("CommandPopover")],
        key_contexts: &[&[Some("CommandPopover")], &[Some("CommandPopover")]],
    },
    Shortcut {
        id: "popover.tab_pressed",
        keys: &["tab"],
        contexts: &[Some("CommandPopover")],
        key_contexts: &[&[Some("CommandPopover")]],
    },
    Shortcut {
        id: "popover.navigate_back",
        keys: &["alt-backspace", "alt-left"],
        contexts: &[Some("CommandPopover")],
        key_contexts: &[&[Some("CommandPopover")], &[Some("CommandPopover")]],
    },
    Shortcut {
        id: "popover.dismiss",
        keys: &["escape"],
        contexts: &[Some("CommandPopover")],
        key_contexts: &[&[Some("CommandPopover")]],
    },
    Shortcut {
        id: "popover.next_tab",
        keys: &["ctrl-tab"],
        contexts: &[Some("CommandPopover")],
        key_contexts: &[&[Some("CommandPopover")]],
    },
    Shortcut {
        id: "popover.previous_tab",
        keys: &["ctrl-shift-tab"],
        contexts: &[Some("CommandPopover")],
        key_contexts: &[&[Some("CommandPopover")]],
    },
    Shortcut {
        id: "menu.dismiss_menu",
        keys: &["escape"],
        contexts: &[Some("Menu")],
        key_contexts: &[&[Some("Menu")]],
    },
    Shortcut {
        id: "menu.highlight_previous",
        keys: &["up"],
        contexts: &[Some("Menu")],
        key_contexts: &[&[Some("Menu")]],
    },
    Shortcut {
        id: "menu.highlight_next",
        keys: &["down"],
        contexts: &[Some("Menu")],
        key_contexts: &[&[Some("Menu")]],
    },
    Shortcut {
        id: "menu.confirm_highlighted",
        keys: &["enter"],
        contexts: &[Some("Menu")],
        key_contexts: &[&[Some("Menu")]],
    },
    Shortcut {
        id: "project_colors.previous_color",
        keys: &["left", "up"],
        contexts: &[Some("ProjectColors")],
        key_contexts: &[&[Some("ProjectColors")], &[Some("ProjectColors")]],
    },
    Shortcut {
        id: "project_colors.next_color",
        keys: &["right", "down"],
        contexts: &[Some("ProjectColors")],
        key_contexts: &[&[Some("ProjectColors")], &[Some("ProjectColors")]],
    },
    Shortcut {
        id: "project_colors.choose_color",
        keys: &["enter"],
        contexts: &[Some("ProjectColors")],
        key_contexts: &[&[Some("ProjectColors")]],
    },
    Shortcut {
        id: "project_colors.dismiss_colors",
        keys: &["escape"],
        contexts: &[Some("ProjectColors")],
        key_contexts: &[&[Some("ProjectColors")]],
    },
    Shortcut {
        id: "button.activate",
        keys: &["enter", "space"],
        contexts: &[Some("Button")],
        key_contexts: &[&[Some("Button")], &[Some("Button")]],
    },
    Shortcut {
        id: "end_all_sessions_and_quit",
        keys: &[],
        contexts: &[None],
        key_contexts: &[],
    },
    Shortcut {
        id: "show_all",
        keys: &[],
        contexts: &[None],
        key_contexts: &[],
    },
    Shortcut {
        id: "zoom",
        keys: &[],
        contexts: &[None],
        key_contexts: &[],
    },
    Shortcut {
        id: "open_configuration",
        keys: &[],
        contexts: &[None],
        key_contexts: &[],
    },
    Shortcut {
        id: "terminal.close_find",
        keys: &["escape"],
        contexts: &[Some("TerminalFindOpen && !TerminalSearchInput")],
        key_contexts: &[&[Some("TerminalFindOpen && !TerminalSearchInput")]],
    },
];
